@helpdesk_HostAddress = http://localhost:5279

GET {{helpdesk_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{helpdesk_HostAddress}}/api/Ticket/?title=Test2%20Ticket&description=This%20is%20a%20test%20ticket2&
###
GET {{helpdesk_HostAddress}}/api/Ticket/5

###
DELETE {{helpdesk_HostAddress}}/api/Ticket/4

###
POST {{helpdesk_HostAddress}}/api/Ticket
Content-Type: application/json
{
  "title": "Test Ticket 4",
  "description": "This is a test ticket"
}

###
PATCH {{helpdesk_HostAddress}}/api/Ticket/5/status
Content-Type: application/json
{
  "status": "Done"
}

###
GET {{helpdesk_HostAddress}}/api/Ticket?status=2

###
PATCH {{helpdesk_HostAddress}}/api/Ticket/5/assign?AgentId=7